 - name: Test SSH
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: Administrator
    key: ${{ secrets.EC2_SSH_KEY }}
    debug: true
    script: |
      hostname
      whoami
      pwd
